---
language: python
python: "2.7"

before_install:

    # Remove MySQL.
    - sudo apt-get -y purge 'mysql*'
    - sudo apt-get -y autoremove
    - sudo apt-get -y autoclean
    - sudo rm -rf /var/lib/mysql
    - sudo truncate -s 0 /var/log/mysql/error.log

    - sudo apt-get update

install:

    # Install Ansible.
    #- sudo apt-get -y install python-software-properties
    #- sudo apt-add-repository -y ppa:ansible/ansible
    #- sudo apt-get -y install ansible
    #- ansible-playbook --version
    - pip install ansible

script:

    # Check the role/playbook's syntax.
    - ansible-playbook -i inventories/local.ini provisioning/prep.yml --syntax-check

    # Run the role/playbook with ansible-playbook.
    - ansible-playbook -i inventories/local.ini provisioning/prep.yml

    # Check the role/playbook's syntax.
    - ansible-playbook -i inventories/local.ini provisioning/deploy.yml --syntax-check

    # Run the role/playbook with ansible-playbook.
    - ansible-playbook -i inventories/local.ini provisioning/deploy.yml

    # Idempotence Test
    - >
      ansible-playbook -i inventories/local.ini provisioning/deploy.yml
      | grep -q 'changed=0.*failed=0'
      && (echo 'Idempotence test: pass' && exit 0)
      || (echo 'Idempotence test: fail' && exit 1)

    # Some MySQL debugging (show all the logs).
    - "sudo ls -lah /var/log"
    - "sudo cat /var/log/mysql/error.log"

    # Check to make sure we can connect to MySQL.
    - >
      sudo -i mysql -u root -e 'show databases;'
      | grep -q 'performance_schema'
      && (echo 'MariaDB running normally' && exit 0)
      || (echo 'MariaDB not running' && exit 1)

    # Run test
    - ansible-playbook -i inventories/local.ini provisioning/test.yml

    # Verify test
    - >
      ansible-playbook -i inventories/local.ini provisioning/test.yml
      | grep -q 'changed=0.*failed=0'
      && (echo 'Idempotence test: pass' && exit 0)
      || (echo 'Idempotence test: fail' && exit 1)
