---
- name: ensure mariadb is configured to bind to the specified address and port
  ini_file:
    dest: /etc/mysql/my.cnf
    section: mysqld
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { option: bind-address, value: "{{ mariadb_bind_address }}" }
    - { option: port, value: "{{ mariadb_port }}" }
  register: modify_mysql_cnf

- name: restart mariadb
  service:
    name: mysql
    state: restarted
  when: modify_mysql_cnf|changed and mariadb_dockerize_context is not defined
